export const WATCHLIST_LOAD = "WATCHLIST_LOAD";
export const WATCHLIST_SUCCESS = "WATCHLIST_SUCCESS";
export const WATCHLIST_ERROR= "WATCHLIST_ERROR";

export const RECENTLY_VIEWED_SUCCESS = "RECENTLY_VIEWED_SUCCESS";
export const RECENTLY_VIEWED_DELETE= "RECENTLY_VIEWED_DELETE";


export const EDITWATCHLIST_SUCCESS = "EDITWATCHLIST_SUCCESS";